# Generated by Django 2.2.4 on 2019-08-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM_GB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatemodel',
            name='Translate_date',
            field=models.CharField(max_length=25),
        ),
    ]
