# Generated by Django 2.2.4 on 2019-08-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM_GB', '0002_auto_20190825_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatemodel',
            name='Translate_IsInspected',
            field=models.BooleanField(default=False),
        ),
    ]
