# Generated by Django 2.2.4 on 2019-09-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM_GB', '0003_translatemodel_translate_isinspected'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatemodel',
            name='Translate_text_KORLOG',
            field=models.TextField(blank=True, null=True),
        ),
    ]
