# Generated by Django 2.2.4 on 2019-09-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM_GB', '0004_translatemodel_translate_text_korlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatemodel',
            name='Translate_LastEditor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
